version: '3.8'

services:
  carbrand-api:
    build:
      context: .
      dockerfile: CarBrand.Presentation/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"   
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Host=postgres-db;Port=5432;Database=CarBrandDb;Username=postgres;Password=strongPass123#

  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: CarBrandDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongPass123#
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
