// <auto-generated />
using System;
using CarBrand.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarBrand.Infraestructure.Migrations
{
    [DbContext(typeof(CarBrandContext))]
    [Migration("20251023163654_InicialMigration")]
    partial class InicialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarBrand.Domain.Agregate.CarBrandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("25eab2b3-f2f9-428c-9abf-24d8306a9678"),
                            Country = "Japan",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = new Guid("b42b52a8-ebbf-4ff6-a504-7a7eb0d4207f"),
                            Country = "South Korea",
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = new Guid("1bfef6ab-3c97-4bb6-8040-4aba216fb247"),
                            Country = "Germany",
                            Name = "BMW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
